### ISSUE TITLE
Roadmap:

### ISSUE THREAD

**Issue by lemanschik** [lemanschik/src_v8#3]
- [ ] Creating Build Process that is compatible to the current
  - [ ] Put build results into /modules/v8/v8.a /modules/v8/release.x64 /modules/v8/include
  - [ ] Put components/just/modules components/smol
    - [ ] Using components/v8_request_logger to cache gclient 's  result of its operations.
    - [ ] Using components/build to build it self.
